# Copyright IBM Corp All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric-amcl"

[[constraint]]
  branch = "master"
  name = "github.com/miekg/pkcs11"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  revision = "a3b6351eb1ff8e1bfa30b2f55d7e282186ed8fee"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/op/go-logging"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "1967d93db724f4a5c0e101307e96d82ff520a067"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/sykesm/zap-logfmt"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/tools"
  revision = "f60e5f99f0816fc2d9ecb338008ea420248d2943"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.20.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
